server:
  port: 80
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr_app
    password: root123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
